apiVersion: apps/v1
kind: Deployment
metadata:
  name: amit-deployment
  labels:
    app: new
spec:
  replicas: 3
  selector:
    matchLabels:
      app: new
  template:
    metadata:
      labels:
        app: new
    spec:
      containers:
      - name: amit-container
        image: amitmishra220/image1:latest
        ports:
        - containerPort: 80
